4.1 Exercise on Functions:

TASK 1

Create a Python program that converts between different units of measurement.

In [51]:
def convert_length(value, unit):
    """
    Change length between meters and feet.
    """
    if unit == 'm':
        return value * 3.28084  # Change meters to feet
    elif unit == 'ft':
        return value / 3.28084  # Change feet to meters
    else:
        raise ValueError("Wrong unit for length.")

def convert_weight(value, unit):
    """
    Change weight between kg and lbs.
    """
    if unit == 'kg':
        return value * 2.20462  # Change kg to lbs
    elif unit == 'lbs':
        return value / 2.20462  # Change lbs to kg
    else:
        raise ValueError("Wrong unit for weight.")

def convert_volume(value, unit):
    """
    Change volume between liters and gallons.
    """
    if unit == 'L':
        return value * 0.264172  # Change liters to gallons
    elif unit == 'gal':
        return value / 0.264172  # Change gallons to liters
    else:
        raise ValueError("Wrong unit for volume.")

def main():
    print("Unit Conversion Program")
    print("1. Length: meters to feet or feet to meters")
    print("2. Weight: kg to lbs or lbs to kg")
    print("3. Volume: liters to gallons or gallons to liters")

    try:
        choice = int(input("Choose conversion type (1/2/3): "))
        value = float(input("Enter value to convert: "))

        if choice == 1:
            unit = input("Enter unit (m for meters, ft for feet): ").strip().lower()
            result = convert_length(value, unit)
            print(f"Converted value: {result:.2f}")
        elif choice == 2:
            unit = input("Enter unit (kg for kilograms, lbs for pounds): ").strip().lower()
            result = convert_weight(value, unit)
            print(f"Converted value: {result:.2f}")
        elif choice == 3:
            unit = input("Enter unit (L for liters, gal for gallons): ").strip().lower()
            result = convert_volume(value, unit)
            print(f"Converted value: {result:.2f}")
        else:
            print("Wrong choice. Pick 1, 2, or 3.")
    except ValueError as e:
        print(f"Error: {e}. Enter correct number and unit.")

if __name__ == "__main__":
    main()

Unit Conversion Program
1. Length: meters to feet or feet to meters
2. Weight: kg to lbs or lbs to kg
3. Volume: liters to gallons or gallons to liters
Choose conversion type (1/2/3): 2
Enter value to convert: 5
Enter unit (kg for kilograms, lbs for pounds): lbs
Converted value: 2.27


TASK 2

 Create a Python program that performs various mathematical operations on a list of numbers

In [49]:
def find_sum(numbers):
    """
    Add all numbers in the list and return the total.
    """
    return sum(numbers)

def find_average(numbers):
    """
    Calculate the average by dividing the total by the number of items.
    """
    return sum(numbers) / len(numbers)

def find_maximum(numbers):
    """
    Find and return the largest number in the list.
    """
    return max(numbers)

def find_minimum(numbers):
    """
    Find and return the smallest number in the list.
    """
    return min(numbers)

def main():
    print("Math Operations on a List")
    print("1. Find Sum")
    print("2. Find Average")
    print("3. Find Maximum")
    print("4. Find Minimum")

    try:
        choice = int(input("Choose an operation (1/2/3/4): "))  # Ask user which operation to do
        numbers = list(map(float, input("Enter numbers separated by spaces: ").split()))  # Get list of numbers

        if not numbers:
            raise ValueError("List is empty. Enter some numbers.")  # Check if list is empty

        if choice == 1:
            result = find_sum(numbers)  # Call function to find sum
        elif choice == 2:
            result = find_average(numbers)  # Call function to find average
        elif choice == 3:
            result = find_maximum(numbers)  # Call function to find max
        elif choice == 4:
            result = find_minimum(numbers)  # Call function to find min
        else:
            print("Invalid choice. Pick 1, 2, 3, or 4.")  # Handle wrong input
            return

        print(f"Result: {result:.2f}")  # Show final answer
    except ValueError as e:
        print(f"Error: {e}. Enter numbers correctly.")  # Handle wrong inputs

if __name__ == "__main__":
    main()


Math Operations on a List
1. Find Sum
2. Find Average
3. Find Maximum
4. Find Minimum
Choose an operation (1/2/3/4): 1
Enter numbers separated by spaces: 4 6 8
Result: 18.00


4.2 Exercise on List Manipulation:

 Write a Python function that extracts every other element from a list, starting from the first element

In [52]:
def extract_every_other(lst):
    """
    This function takes a list and returns a new list
    containing every other element from the original list.
    """
    return lst[::2]  # Select every second element from the list

# Example usage
numbers = [4, 5, 6, 7, 8, 9]  # Sample list
result = extract_every_other(numbers)  # Call function
print(result)  # Display result

[4, 6, 8]


 2. Slice a Sublist:

 Write a Python function that returns a sublist from a given list, starting from a specified index and
 ending at another specified index.

In [53]:
def get_sublist(lst, start, end):
    return lst[start:end+1]  # Slice the list from 'start' to 'end' (inclusive)

# Example usage
lst = [1, 2, 3, 4, 5, 6]  # Given list
start = 2  # Starting index
end = 4  # Ending index

result = get_sublist(lst, start, end)  # Get the sublist
print(result)  # Print the result


[3, 4, 5]


 3. Reverse a List Using Slicing:

Write a Python function that reverses a list using slicing.

In [54]:
def reverse_slicing(lst):
    return lst[::-1]  # Use slicing to reverse the list

# Example usage
lst = [1, 2, 3, 4, 5]  # Given list
result = reverse_slicing(lst)  # Reverse the list
print(result)  # Print the reversed list


[5, 4, 3, 2, 1]


4. Remove the First and Last Elements:

 Write a Python function that removes the first and last elements of a list and returns the resulting
 sublist.

In [55]:
def remove_first_last(lst):
    return lst[1:-1]  # Slice the list to remove the first and last elements

# Example usage
lst = [1, 2, 3, 4, 5]  # Given list
result = remove_first_last(lst)  # Remove first and last elements
print(result)  # Print the resulting sublist


[2, 3, 4]


5. Get the First n Elements:

Write a Python function that extracts the first n elements from a list.

In [56]:
def get_first_n(lst, n):
    return lst[:n]  # Slice the list to get the first n elements

# Example usage
lst = [1, 2, 3, 4, 5]  # Given list
n = 3  # Number of elements to extract
result = get_first_n(lst, n)  # Get the first n elements
print(result)  # Print the result


[1, 2, 3]


6. Extract Elements from the End:

Write a Python function that extracts the last n elements of a list using slicing.

In [57]:
def get_last_n(lst, n):
    return lst[-n:]  # Slice the list to get the last n elements

# Example usage
lst = [1, 2, 3, 4, 5]  # Given list
n = 2  # Number of elements to extract
result = get_last_n(lst, n)  # Get the last n elements
print(result)  # Print the result


[4, 5]


7. Extract Elements in Reverse Order:

Write a Python function that extracts a list of elements in reverse order starting from the second-to-last
 element and skipping one element in between.

In [58]:
def reverse_skip(lst):
    return lst[-2::-2]  # Start from second-to-last and skip every other element moving backward

# Example usage
lst = [1, 2, 3, 4, 5, 6]  # Given list
result = reverse_skip(lst)  # Extract every second element in reverse order
print(result)  # Print the result


[5, 3, 1]


**4.3 Exercise on Nested List:**

 1. Flatten a Nested List:

Write a Python function that takes a nested list and flattens it into a single list, where all the elements
 are in a single dimension.

In [59]:
def flatten(lst):
    # Use a list comprehension to flatten the list
    return [item for sublist in lst for item in sublist]

# Example usage
nested_lst = [[1, 2], [3, 4], [5]]  # Given nested list
result = flatten(nested_lst)  # Flatten the nested list
print(result)  # Print the flattened list


[1, 2, 3, 4, 5]


2. Accessing Nested List Elements:

Write a Python function that extracts a specific element from a nested list given its indices.

In [60]:
def access_nested_element(lst, indices):
    # Use the indices to access the element in the nested list
    for index in indices:
        lst = lst[index]  # Access the sublist at the given index
    return lst  # Return the final element

# Example usage
lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]  # Given nested list
indices = [1, 2]  # Indices to access the element
result = access_nested_element(lst, indices)  # Get the element at the given indices
print(result)  # Print the result


6


 3. Sum of All Elements in a Nested List:

Write a Python function that calculates the sum of all the numbers in a nested list (regardless of depth).

In [61]:
def sum_nested(lst):
    total = 0
    for item in lst:
        if isinstance(item, list):  # If the item is a list, call sum_nested recursively
            total += sum_nested(item)
        else:
            total += item  # If it's not a list, add the value to the total
    return total

# Example usage
lst = [[1, 2], [3, [4, 5]], 6]  # Given nested list
result = sum_nested(lst)  # Calculate the sum of all elements
print(result)  # Print the result


21


 4. Remove Specific Element from a Nested List:

Write a Python function that removes all occurrences of a specific element from a nested list.

In [62]:
def remove_element(lst, elem):
    for i in range(len(lst)):
        if isinstance(lst[i], list):  # If the item is a list, call remove_element recursively
            lst[i] = remove_element(lst[i], elem)
        else:
            if lst[i] == elem:  # Remove the element if it matches
                lst[i] = None  # Replace with None temporarily
    # Remove any None values
    lst = [x for x in lst if x is not None]
    return lst

# Example usage
lst = [[1, 2], [3, 2], [4, 5]]  # Given nested list
elem = 2  # Element to remove
result = remove_element(lst, elem)  # Remove the element
print(result)  # Print the modified list


[[1], [3], [4, 5]]


 5. Find the Maximum Element in a Nested List:

Write a Python function that finds the maximum element in a nested list (regardless of depth).

In [63]:
def find_max(lst):
    max_elem = float('-inf')  # Start with a very low value
    for item in lst:
        if isinstance(item, list):  # If the item is a list, call find_max recursively
            max_elem = max(max_elem, find_max(item))
        else:
            max_elem = max(max_elem, item)  # If it's not a list, compare the item with max_elem
    return max_elem

# Example usage
lst = [[1, 2], [3, [4, 5]], 6]  # Given nested list
result = find_max(lst)  # Find the maximum element
print(result)  # Print the result


6


6. Count Occurrences of an Element in a Nested List:

Write a Python function that counts how many times a specific element appears in a nested list.

In [64]:
def count_occurrences(lst, elem):
    count = 0
    for item in lst:
        if isinstance(item, list):  # If the item is a list, call count_occurrences recursively
            count += count_occurrences(item, elem)
        else:
            if item == elem:  # If it's not a list and matches elem, increment the count
                count += 1
    return count

# Example usage
lst = [[1, 2], [2, 3], [2, 4]]  # Given nested list
elem = 2  # Element to count occurrences
result = count_occurrences(lst, elem)  # Count the occurrences of elem
print(result)  # Print the result


3


7. Flatten a List of Lists of Lists:

Write a Python function that flattens a list of lists of lists into a single list, regardless of the depth.

In [65]:
def deep_flatten(lst):
    flattened = []  # Initialize an empty list to store the flattened elements
    for item in lst:
        if isinstance(item, list):  # If the item is a list, call deep_flatten recursively
            flattened.extend(deep_flatten(item))
        else:
            flattened.append(item)  # If it's not a list, add the item to the flattened list
    return flattened

# Example usage
lst = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]  # Given deeply nested list
result = deep_flatten(lst)  # Flatten the deeply nested list
print(result)  # Print the result


[1, 2, 3, 4, 5, 6, 7, 8]


 8. Nested List Average:

Write a Python function that calculates the average of all elements in a nested list.

In [66]:
def average_nested(lst):
    total = 0
    count = 0
    for item in lst:
        if isinstance(item, list):  # If the item is a list, call average_nested recursively
            sub_total, sub_count = average_nested(item)
            total += sub_total
            count += sub_count
        else:
            total += item  # If it's not a list, add the item to the total
            count += 1  # Increment the count for each item
    return total, count  # Return total sum and count of elements

# Example usage
lst = [[1, 2], [3, 4], [5, 6]]  # Given nested list
total, count = average_nested(lst)  # Calculate the total and count
average = total / count  # Calculate the average
print(average)  # Print the average


3.5


10.1 Basic Vector and Matrix Operation with Numpy.

 Problem- 1: Array Creation:

In [67]:
import numpy as np

# 1. Initialize an empty array with size 2X2
empty_array = np.empty((2, 2))  # Creates an empty array of shape 2x2
print("Empty Array (2x2):")
print(empty_array)

# 2. Initialize an all one array with size 4X2
ones_array = np.ones((4, 2))  # Creates an array of ones with shape 4x2
print("\nAll Ones Array (4x2):")
print(ones_array)

# 3. Return a new array of given shape and type, filled with fill value
shape = (3, 3)  # Example shape (3x3)
fill_value = 7  # Fill value to use for the array
filled_array = np.full(shape, fill_value)  # Creates an array of shape (3x3) filled with value 7
print("\nArray Filled with Value 7 (3x3):")
print(filled_array)

# 4. Return a new array of zeros with same shape and type as a given array
reference_array = np.array([[5, 6], [7, 8]])  # A reference array to match shape
zeros_like_array = np.zeros_like(reference_array)  # Creates an array of zeros with the same shape and type as reference_array
print("\nZeros-like Array with Same Shape as Reference Array:")
print(zeros_like_array)

# 5. Return a new array of ones with same shape and type as a given array
ones_like_array = np.ones_like(reference_array)  # Creates an array of ones with the same shape and type as reference_array
print("\nOnes-like Array with Same Shape as Reference Array:")
print(ones_like_array)

# 6. Convert an existing list to a NumPy array
new_list = [1, 2, 3, 4]  # A simple Python list
numpy_array = np.array(new_list)  # Converts the Python list to a NumPy array
print("\nConverted List to NumPy Array:")
print(numpy_array)


Empty Array (2x2):
[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]

All Ones Array (4x2):
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

Array Filled with Value 7 (3x3):
[[7 7 7]
 [7 7 7]
 [7 7 7]]

Zeros-like Array with Same Shape as Reference Array:
[[0 0]
 [0 0]]

Ones-like Array with Same Shape as Reference Array:
[[1 1]
 [1 1]]

Converted List to NumPy Array:
[1 2 3 4]


 Problem- 2: Array Manipulation: Numerical Ranges and Array indexing:

In [68]:
import numpy as np

# 1. Create an array with values ranging from 10 to 49
array_1 = np.arange(10, 50)  # Create an array from 10 to 49
print("Array with values from 10 to 49:")
print(array_1)

# 2. Create a 3X3 matrix with values ranging from 0 to 8
matrix_2 = np.arange(9).reshape(3, 3)  # Create an array from 0 to 8 and reshape it into a 3x3 matrix
print("\n3X3 matrix with values ranging from 0 to 8:")
print(matrix_2)

# 3. Create a 3X3 identity matrix
identity_matrix = np.eye(3)  # Create a 3x3 identity matrix (1s on the diagonal, 0s elsewhere)
print("\n3X3 Identity matrix:")
print(identity_matrix)

# 4. Create a random array of size 30 and find the mean of the array
random_array = np.random.random(30)  # Create a random array of 30 values
mean_value = random_array.mean()  # Find the mean of the random array
print("\nRandom array of size 30:")
print(random_array)
print("Mean of the array:", mean_value)

# 5. Create a 10X10 array with random values and find the minimum and maximum values
array_5 = np.random.random((10, 10))  # Create a 10x10 array with random values
min_value = array_5.min()  # Find the minimum value in the array
max_value = array_5.max()  # Find the maximum value in the array
print("\n10X10 array with random values:")
print(array_5)
print("Minimum value:", min_value)
print("Maximum value:", max_value)

# 6. Create a zero array of size 10 and replace the 5th element with 1
zero_array = np.zeros(10)  # Create an array of 10 zeros
zero_array[4] = 1  # Replace the 5th element (index 4) with 1
print("\nZero array with the 5th element replaced by 1:")
print(zero_array)

# 7. Reverse an array arr = [1, 2, 0, 0, 4, 0]
arr = np.array([1, 2, 0, 0, 4, 0])  # Create a numpy array
reversed_arr = arr[::-1]  # Reverse the array using slicing
print("\nReversed array:")
print(reversed_arr)

# 8. Create a 2d array with 1 on the border and 0 inside
border_array = np.ones((5, 5))  # Create a 5x5 array filled with ones
border_array[1:-1, 1:-1] = 0  # Set the inner elements to 0 (excluding the border)
print("\n2D array with 1 on border and 0 inside:")
print(border_array)

# 9. Create an 8X8 matrix and fill it with a checkerboard pattern
checkerboard = np.zeros((8, 8), dtype=int)  # Create an 8x8 array filled with zeros
checkerboard[1::2, ::2] = 1  # Set alternating elements to 1
checkerboard[::2, 1::2] = 1  # Set alternating elements to 1 in the other direction
print("\n8X8 Checkerboard pattern matrix:")
print(checkerboard)


Array with values from 10 to 49:
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

3X3 matrix with values ranging from 0 to 8:
[[0 1 2]
 [3 4 5]
 [6 7 8]]

3X3 Identity matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Random array of size 30:
[0.32989239 0.74249809 0.55695496 0.99677171 0.22350779 0.29950847
 0.67099275 0.27231211 0.37868343 0.13856608 0.80104526 0.69841857
 0.99683007 0.03360952 0.4489821  0.76669684 0.0137519  0.10575745
 0.03188191 0.2639641  0.91388376 0.62991274 0.24995476 0.75436719
 0.50593344 0.73027625 0.89921771 0.18100885 0.46962139 0.10256079]
Mean of the array: 0.47357874623811413

10X10 array with random values:
[[0.11615117 0.00947371 0.97682343 0.06299092 0.28839573 0.81271531
  0.30192592 0.54091419 0.55955987 0.97826422]
 [0.79700436 0.78088641 0.90113286 0.92434484 0.61639659 0.52203512
  0.94778183 0.83292919 0.99013298 0.03615597]
 [0.07788354 0.0403413  0.32089845 0.82367863 0.

Problem- 3: Array Operations:

In [69]:
import numpy as np

# Define the arrays
x = np.array([[1, 2], [3, 5]])  # 2x2 matrix
y = np.array([[5, 6], [7, 8]])  # 2x2 matrix
v = np.array([9, 10])           # 1D array with 2 elements
w = np.array([11, 12])          # 1D array with 2 elements

# 1. Add the two arrays
add_result = x + y  # Element-wise addition of arrays x and y
print("Addition of x and y:")
print(add_result)

# 2. Subtract the two arrays
subtract_result = x - y  # Element-wise subtraction of arrays x and y
print("\nSubtraction of x and y:")
print(subtract_result)

# 3. Multiply the array with any integers of your choice
multiply_result = x * 2  # Multiply every element in array x by 2
print("\nMultiplying x by 2:")
print(multiply_result)

# 4. Find the square of each element of the array
square_result = np.square(x)  # Square each element of array x
print("\nSquare of each element in x:")
print(square_result)

# 5. Find the dot product between:
# v and w
dot_v_w = np.dot(v, w)  # Dot product of v and w (scalar result)
print("\nDot product of v and w:")
print(dot_v_w)

# x and v
dot_x_v = np.dot(x, v)  # Dot product of x and v (matrix-vector multiplication)
print("\nDot product of x and v:")
print(dot_x_v)

# x and y
dot_x_y = np.dot(x, y)  # Dot product of x and y (matrix-matrix multiplication)
print("\nDot product of x and y:")
print(dot_x_y)

# 6. Concatenate x and y along rows and concatenate v and w along columns
concat_x_y_row = np.concatenate((x, y), axis=0)  # Concatenate x and y along rows (stack vertically)
print("\nConcatenating x and y along rows:")
print(concat_x_y_row)

concat_v_w_column = np.concatenate((v.reshape(-1, 1), w.reshape(-1, 1)), axis=1)  # Reshape v and w to column vectors, then concatenate along columns
print("\nConcatenating v and w along columns:")
print(concat_v_w_column)

# 7. Concatenate x and v; if an error occurs, observe and explain
try:
    concat_x_v = np.concatenate((x, v), axis=0)  # Try concatenating x and v along rows
    print("\nConcatenating x and v along rows:")
    print(concat_x_v)
except Exception as e:
    print("\nError occurred while concatenating x and v:")
    print(e)


Addition of x and y:
[[ 6  8]
 [10 13]]

Subtraction of x and y:
[[-4 -4]
 [-4 -3]]

Multiplying x by 2:
[[ 2  4]
 [ 6 10]]

Square of each element in x:
[[ 1  4]
 [ 9 25]]

Dot product of v and w:
219

Dot product of x and v:
[29 77]

Dot product of x and y:
[[19 22]
 [50 58]]

Concatenating x and y along rows:
[[1 2]
 [3 5]
 [5 6]
 [7 8]]

Concatenating v and w along columns:
[[ 9 11]
 [10 12]]

Error occurred while concatenating x and v:
all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


 Problem- 4: Matrix Operations:

For the following arrays:
 A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);
 Prove following with Numpy:

 1. Prove A.A−1 = I.

In [70]:
import numpy as np

# Matrix A
A = np.array([[3, 4], [7, 8]])

# Find the inverse of A
A_inv = np.linalg.inv(A)

# Multiply A by A's inverse
result = np.dot(A, A_inv)

# Output the result to verify it is the identity matrix
print("A * A^-1 =\n", result)


A * A^-1 =
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]


 2. Prove AB= BA.

In [71]:
# Matrix B
B = np.array([[5, 3], [2, 1]])

# Compute AB and BA
AB = np.dot(A, B)
BA = np.dot(B, A)

# Output both products
print("AB =\n", AB)
print("BA =\n", BA)

# Check if AB equals BA
if np.array_equal(AB, BA):
    print("AB = BA")
else:
    print("AB != BA")


AB =
 [[23 13]
 [51 29]]
BA =
 [[36 44]
 [13 16]]
AB != BA


 3. Prove (AB)T = BTAT.

In [72]:
# Compute (AB)^T
AB_T = np.transpose(AB)

# Compute B^T * A^T
B_T = np.transpose(B)
A_T = np.transpose(A)
B_T_A_T = np.dot(B_T, A_T)

# Output both results
print("(AB)^T =\n", AB_T)
print("B^T * A^T =\n", B_T_A_T)

# Check if (AB)^T equals B^T * A^T
if np.array_equal(AB_T, B_T_A_T):
    print("(AB)^T = B^T * A^T")
else:
    print("(AB)^T != B^T * A^T")


(AB)^T =
 [[23 51]
 [13 29]]
B^T * A^T =
 [[23 51]
 [13 29]]
(AB)^T = B^T * A^T


Solve the following system of Linear equation using Inverse Methods.
 2x −3y+z =−1
 x −y+2z =−3
 3x +y−z =9

In [73]:
# Coefficient matrix A
A = np.array([[2, -3, 1],
              [1, -1, 2],
              [3, 1, -1]])

# Constants matrix B
B = np.array([-1, -3, 9])

# Find the inverse of A
A_inv = np.linalg.inv(A)

# Solve for X (the variables x, y, z)
X = np.dot(A_inv, B)

# Output the solution for x, y, z
print("Solution for x, y, z:", X)


Solution for x, y, z: [ 2.  1. -2.]


10.2 Experiment: How Fast is Numpy?

 1. Element-wise Addition:

2. Element-wise Multiplication

 3. Dot Product

4. Matrix Multiplication

In [ ]:
import numpy as np  # Import NumPy for efficient operations
import time  # Import time module to measure execution time

# Define the size of the arrays
size = 1_000_000  # 1 million elements

### 1. Element-wise Addition ###

# Using Python Lists
list1 = [i for i in range(size)]
list2 = [i for i in range(size)]

start_time = time.time()  # Start timing
list_sum = [list1[i] + list2[i] for i in range(size)]  # Perform addition
end_time = time.time()  # End timing

print("Time for element-wise addition using Python lists:", end_time - start_time, "seconds")

# Using NumPy Arrays
array1 = np.arange(size)
array2 = np.arange(size)

start_time = time.time()
array_sum = array1 + array2  # Perform addition using NumPy
end_time = time.time()

print("Time for element-wise addition using NumPy:", end_time - start_time, "seconds")

### 2. Element-wise Multiplication ###

# Using Python Lists
start_time = time.time()
list_product = [list1[i] * list2[i] for i in range(size)]  # Multiply elements
end_time = time.time()

print("Time for element-wise multiplication using Python lists:", end_time - start_time, "seconds")

# Using NumPy Arrays
start_time = time.time()
array_product = array1 * array2  # Multiply elements using NumPy
end_time = time.time()

print("Time for element-wise multiplication using NumPy:", end_time - start_time, "seconds")

### 3. Dot Product ###

# Using Python Lists
start_time = time.time()
dot_product_list = sum(list1[i] * list2[i] for i in range(size))  # Compute dot product
end_time = time.time()

print("Time for dot product using Python lists:", end_time - start_time, "seconds")

# Using NumPy Arrays
start_time = time.time()
dot_product_numpy = np.dot(array1, array2)  # Compute dot product using NumPy
end_time = time.time()

print("Time for dot product using NumPy:", end_time - start_time, "seconds")

### 4. Matrix Multiplication ###

# Define matrix size
matrix_size = 1000  # 1000x1000 matrix

# Using Python Lists
matrix1 = [[1 for _ in range(matrix_size)] for _ in range(matrix_size)]
matrix2 = [[1 for _ in range(matrix_size)] for _ in range(matrix_size)]

start_time = time.time()

# Perform matrix multiplication manually using nested loops
result_matrix = [[sum(matrix1[i][k] * matrix2[k][j] for k in range(matrix_size)) for j in range(matrix_size)] for i in range(matrix_size)]

end_time = time.time()
print("Time for matrix multiplication using Python lists:", end_time - start_time, "seconds")

# Using NumPy Arrays
array1 = np.ones((matrix_size, matrix_size))
array2 = np.ones((matrix_size, matrix_size))

start_time = time.time()

result_array = np.dot(array1, array2)  # Use NumPy's dot function for fast multiplication

end_time = time.time()
print("Time for matrix multiplication using NumPy:", end_time - start_time, "seconds")


Time for element-wise addition using Python lists: 0.19823002815246582 seconds
Time for element-wise addition using NumPy: 0.0024013519287109375 seconds
Time for element-wise multiplication using Python lists: 0.17896103858947754 seconds
Time for element-wise multiplication using NumPy: 0.0022344589233398438 seconds
Time for dot product using Python lists: 0.2508513927459717 seconds
Time for dot product using NumPy: 0.002490997314453125 seconds
